package com.example.demo.a101001_01.repository;

import com.example.demo.a101001_01.dto.database.Ankens;
import com.example.demo.a101001_01.dto.database.AnkensExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnkensMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    long countByExample(AnkensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    int deleteByExample(AnkensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ankenNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    int insert(Ankens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    int insertSelective(Ankens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    List<Ankens> selectByExample(AnkensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    Ankens selectByPrimaryKey(String ankenNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ankens record, @Param("example") AnkensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ankens record, @Param("example") AnkensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ankens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ankens record);
}