package com.example.demo.a101001_01.dto.database;

public class Ankens {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_schema.ankens.anken_number
     *
     * @mbg.generated
     */
    private String ankenNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_schema.ankens.anken_name
     *
     * @mbg.generated
     */
    private String ankenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_schema.ankens.anken_number
     *
     * @return the value of sample_schema.ankens.anken_number
     *
     * @mbg.generated
     */
    public String getAnkenNumber() {
        return ankenNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_schema.ankens.anken_number
     *
     * @param ankenNumber the value for sample_schema.ankens.anken_number
     *
     * @mbg.generated
     */
    public void setAnkenNumber(String ankenNumber) {
        this.ankenNumber = ankenNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_schema.ankens.anken_name
     *
     * @return the value of sample_schema.ankens.anken_name
     *
     * @mbg.generated
     */
    public String getAnkenName() {
        return ankenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_schema.ankens.anken_name
     *
     * @param ankenName the value for sample_schema.ankens.anken_name
     *
     * @mbg.generated
     */
    public void setAnkenName(String ankenName) {
        this.ankenName = ankenName;
    }
}