package com.example.demo.a101001_01.dto.database;

import java.util.ArrayList;
import java.util.List;

public class AnkensExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public AnkensExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAnkenNumberIsNull() {
            addCriterion("anken_number is null");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberIsNotNull() {
            addCriterion("anken_number is not null");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberEqualTo(String value) {
            addCriterion("anken_number =", value, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberNotEqualTo(String value) {
            addCriterion("anken_number <>", value, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberGreaterThan(String value) {
            addCriterion("anken_number >", value, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberGreaterThanOrEqualTo(String value) {
            addCriterion("anken_number >=", value, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberLessThan(String value) {
            addCriterion("anken_number <", value, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberLessThanOrEqualTo(String value) {
            addCriterion("anken_number <=", value, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberLike(String value) {
            addCriterion("anken_number like", value, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberNotLike(String value) {
            addCriterion("anken_number not like", value, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberIn(List<String> values) {
            addCriterion("anken_number in", values, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberNotIn(List<String> values) {
            addCriterion("anken_number not in", values, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberBetween(String value1, String value2) {
            addCriterion("anken_number between", value1, value2, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNumberNotBetween(String value1, String value2) {
            addCriterion("anken_number not between", value1, value2, "ankenNumber");
            return (Criteria) this;
        }

        public Criteria andAnkenNameIsNull() {
            addCriterion("anken_name is null");
            return (Criteria) this;
        }

        public Criteria andAnkenNameIsNotNull() {
            addCriterion("anken_name is not null");
            return (Criteria) this;
        }

        public Criteria andAnkenNameEqualTo(String value) {
            addCriterion("anken_name =", value, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameNotEqualTo(String value) {
            addCriterion("anken_name <>", value, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameGreaterThan(String value) {
            addCriterion("anken_name >", value, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameGreaterThanOrEqualTo(String value) {
            addCriterion("anken_name >=", value, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameLessThan(String value) {
            addCriterion("anken_name <", value, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameLessThanOrEqualTo(String value) {
            addCriterion("anken_name <=", value, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameLike(String value) {
            addCriterion("anken_name like", value, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameNotLike(String value) {
            addCriterion("anken_name not like", value, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameIn(List<String> values) {
            addCriterion("anken_name in", values, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameNotIn(List<String> values) {
            addCriterion("anken_name not in", values, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameBetween(String value1, String value2) {
            addCriterion("anken_name between", value1, value2, "ankenName");
            return (Criteria) this;
        }

        public Criteria andAnkenNameNotBetween(String value1, String value2) {
            addCriterion("anken_name not between", value1, value2, "ankenName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sample_schema.ankens
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}